<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>blade</string>
	</array>
	<key>name</key>
	<string>Blade</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.php</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\{\{</string>
			<key>name</key>
			<string>keyword.source.open.blade</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\}\}</string>
			<key>name</key>
			<string>keyword.source.tag.close.blade</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\@</string>
			<key>name</key>
			<string>support.class.tag.start.blade</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\@[A-Za-z_][A-Za-z_0-9]*$</string>
			<key>name</key>
			<string>keyword.source.compiler.end.blade</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\(</string>
			<key>name</key>
			<string>entity.name.par.blade</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((end|)(yield_|)section)|((end|)foreach)|(yield)\b</string>
			<key>name</key>
			<string>keyword.source.compiler.blade</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\{\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.varible.blade</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}\}</string>
			<key>name</key>
			<string>keyword.source.compiler.start.blade</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[A-Za-z_.][A-Za-z_0-9.]+</string>
					<key>name</key>
					<string>entity.name.varible.two.blade</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?=\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>compiler.variable.blade</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.blade</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>keyword.source.compiler.start.blade</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\'([A-Za-z_.][A-Za-z_0-9.]+)\'</string>
					<key>name</key>
					<string>string.function.blade</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>&amp;lt;!</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>compiler.variable.blade</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>punctuation.definition.tag.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\'([A-Za-z_.][A-Za-z_0-9.]+)\'</string>
					<key>name</key>
					<string>entity.name.function.blade</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.blade</string>
	<key>uuid</key>
	<string>37d771c4-f1b0-4e9c-a50e-d060fb8823a1</string>
</dict>
</plist>
