<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>blade.php</string>
	</array>
	<key>name</key>
	<string>Blade</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.constant.language.compiler.tag.blade</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.compiler.blade</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>End compiler tags: @yield_section</string>
			<key>match</key>
			<string>(\@)([A-Za-z0-9_]+)$</string>
			<key>name</key>
			<string>call.compiler.end.blade</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\@)([A-Za-z0-9_]+)(?=(|\s*|)\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.constant.language.compiler.tag.blade</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.compiler.blade</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Compiler tags with parameters: @section()</string>
			<key>contentName</key>
			<string>compiler.params.blade</string>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>call.compiler.blade</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Operands: as = + - &gt; &lt;</string>
					<key>match</key>
					<string>\b(as)\b|([=&gt;&lt;])</string>
					<key>name</key>
					<string>keyword.operand.blade</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Variable names $somthing</string>
					<key>match</key>
					<string>\$([A-Za-z_.]+)</string>
					<key>name</key>
					<string>Variable.blade</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[0-9]</string>
					<key>name</key>
					<string>constant.numeric.blade</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\'([A-Za-z_0-9. ]+)\'</string>
					<key>name</key>
					<string>string.compiler.parameter.blade</string>
				</dict>
				<dict>
					<key>match</key>
					<string>([A-Za-z_]+)</string>
					<key>name</key>
					<string>support.function.blade</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\{)(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.constant.language.echo.wrapper.blade</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>PHP echo wrapper</string>
			<key>contentName</key>
			<string>echo.wrapper.params.blade</string>
			<key>end</key>
			<string>(\})(\})</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.constant.language.echo.wrapper.close.blade</string>
				</dict>
			</dict>
			<key>name</key>
			<string>call.echo.wrapper.blade</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>Operands: as = + - &gt; &lt;</string>
					<key>match</key>
					<string>\b(as)\b|([=&gt;&lt;\+])</string>
					<key>name</key>
					<string>keyword.operand.blade</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Variable names $somthing</string>
					<key>match</key>
					<string>\$([A-Za-z_.]+)</string>
					<key>name</key>
					<string>variable.name.blade</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[0-9]</string>
					<key>name</key>
					<string>constant.numeric.blade</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\'([A-Za-z_0-9. ]+)\'</string>
					<key>name</key>
					<string>string.compiler.parameter.blade</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.blade</string>
	<key>uuid</key>
	<string>70911d1c-0a7c-4cb5-9771-d71d23d8ab1a</string>
</dict>
</plist>
